//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KodePOSApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Master_KodePOS
    {
        public long IDKodePOS { get; set; }
        public int NoKodePOS { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string Jenis { get; set; }
        public string Kabupaten { get; set; }
        public string Propinsi { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
